### ISSUE TITLE
🚧 remove solutions from `*.challenge.cairo`

### ISSUE THREAD

**Issue by kootsZhin** [quasarlabsXYZ/dvdsn#13]
- right now all the solutions are coded in `*.challenge.cairo`, need to figure out a new way to handle that

**Comment by camheras** [comment]
I didn't understand at first why every test were passing 😅 Maybe keeping test_hack file with "your code here" empty. And create a branch "answers" and start-here like [Starknet Account Tutorial](https://github.com/starknet-edu/starknet-accounts))

**Comment by kootsZhin** [comment]
> I didn't understand at first why every test were passing 😅 Maybe keeping test_hack function with "your code here" empty. And create a branch "answers" and "start-here" like [Starknet Account Tutorial](https://github.com/starknet-edu/starknet-accounts))

Ah yes haha that's the plan, will fix it with #6

**Comment by kootsZhin** [comment]
fixed in #27
